In [37]:
# used for manipulating directory paths
import os
import pandas as pd
import numpy as np

# Plotting library
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # needed to plot 3-D surfaces

# tells matplotlib to embed plots within the notebook
%matplotlib inline

In [38]:
data1 = pd.read_csv("training_new2.csv")
data1 = data1.sample(n=10000)
data1.head()

Store   Date  Dept  Temperature  Fuel_Price  CPI  Unemployment  \
4276       1  31210    10           57           2  211             8   
7302       2  42310    30           65           2  210             8   
27166      3  93011     7           82           3  220             7   
20674      6  32610    35           53           2  212             7   
7156       4  50710    36           56           2  126             7   

       IsHoliday  Weekly_Sales  
4276           0         28208  
7302           0          5275  
27166          0          7903  
20674          0          4238  
7156           0          2014

In [39]:
# getting the correlation matrix
data1.apply(lambda x: x.factorize()[0]).corr()

Store      Date      Dept  Temperature  Fuel_Price       CPI  \
Store         1.000000 -0.018546 -0.040682     0.094960   -0.016282  0.297184   
Date         -0.018546  1.000000 -0.001237     0.084325    0.160254  0.081094   
Dept         -0.040682 -0.001237  1.000000    -0.000384    0.007746 -0.015282   
Temperature   0.094960  0.084325 -0.000384     1.000000    0.080644  0.215831   
Fuel_Price   -0.016282  0.160254  0.007746     0.080644    1.000000  0.477742   
CPI           0.297184  0.081094 -0.015282     0.215831    0.477742  1.000000   
Unemployment  0.334666  0.066907  0.000802    -0.008370    0.264883  0.277629   
IsHoliday     0.007325 -0.136639 -0.010046     0.061530   -0.016715  0.005100   
Weekly_Sales -0.058493  0.022505 -0.022985    -0.008051   -0.009306 -0.039978   

              Unemployment  IsHoliday  Weekly_Sales  
Store             0.334666   0.007325     -0.058493  
Date              0.066907  -0.136639      0.022505  
Dept              0.000802  -0.010046     -0.022985  
Temperature      -0.008370   0.061530     -0.008051  
Fuel_Price        0.264883  -0.016715     -0.009306  
CPI               0.277629   0.005100     -0.039978  
Unemployment      1.000000  -0.014394     -0.015903  
IsHoliday        -0.014394   1.000000      0.007818  
Weekly_Sales     -0.015903   0.007818      1.000000

In [40]:
# drog the high correlated features

def correlation(data_set, threshold):
    col_set = set() #store the name of correlated column
    corr_matrix = data_set.corr()
    for i in range (len(corr_matrix.columns)):
        for j in range (i):
            if abs(corr_matrix.iloc[i,j])>threshold:
                col_name = corr_matrix.columns[i]
                col_set.add(col_name)
    return col_set

In [41]:
# finding the name of column we want to remove

corr_feature = correlation(data1,0.30)
corr_feature

{'Temperature', 'Unemployment'}

In [70]:
# Read the columns into a variable

#x1 = data1["Store"]
#x1 = data1["Date"]
#x1 = data1["Dept"]
x1 = data1["Temperature"]
x2 = data1["Fuel_Price"]
x3 = data1["CPI"]
x4 = data1["Unemployment"]
x5 = data1["IsHoliday"]
y = data1["Weekly_Sales"]
m=y.size
print(x1.shape)
#print(x2.shape)
print(x2.shape)
print(x3.shape)
print(x4.shape)
print(x5.shape)
#print(x6.shape)
#print(x7.shape)

(10000,)
(10000,)
(10000,)
(10000,)
(10000,)


In [71]:
# Convert our variables datatype from series to array :

x1 = np.array(x1)
x2 = np.array(x2)
x3 = np.array(x3)
x4 = np.array(x4)
x5 = np.array(x5)
#x6 = np.array(x6)
#x7 = np.array(x7)
y = np.array(y)

# number of our dataset

n = len(x1)
n

10000

In [72]:
# Create a “ones” matrix :

x_bias = np.ones((n,1))

# Reshape our data so that we can perform operations like addition and multiplication with x_bias

x1_new = np.reshape(x1,(n,1))
x2_new = np.reshape(x2,(n,1))
x3_new = np.reshape(x3,(n,1))
x4_new = np.reshape(x4,(n,1))
x5_new = np.reshape(x5,(n,1))
#x6_new = np.reshape(x6,(n,1))
#x7_new = np.reshape(x7,(n,1))

#Create a major matrix with all the columns:

x_new = np.append(x_bias,x1_new,axis=1)
x_new = np.append(x_new,x2_new,axis=1)
x_new = np.append(x_new,x3_new,axis=1)
x_new = np.append(x_new,x4_new,axis=1)
x_new = np.append(x_new,x5_new,axis=1)
#x_new = np.append(x_new,x6_new,axis=1)
#x_new = np.append(x_new,x7_new,axis=1)


x_new

array([[  1.,  57.,   2., 211.,   8.,   0.],
       [  1.,  65.,   2., 210.,   8.,   0.],
       [  1.,  82.,   3., 220.,   7.,   0.],
       ...,
       [  1.,  59.,   3., 217.,   7.,   0.],
       [  1.,  77.,   3., 215.,   7.,   1.],
       [  1.,  29.,   2., 189.,   9.,   0.]])

In [73]:
#Find transpose of a matrix :

x_new_transpose = np.transpose(x_new)

#Perform multiplication:

x_new_transpose_dot_x_new = x_new_transpose.dot(x_new)

#AFter regularization
lambd = -18
IdentityMatrix= np.zeros((6, 6))
#x_new_transpose_dot_x_new = x_new_transpose_dot_x_new + (lambd*IdentityMatrix)

# find the inverse

temp_1 = np.linalg.inv(x_new_transpose_dot_x_new + (lambd*IdentityMatrix))

#perform multiplication

temp_2 = x_new_transpose.dot(y)

#Finding coefficients :

theta = temp_1.dot(temp_2)

theta

array([32746.92307168,    90.29125834,  1552.62795046,  -140.14784242,
         434.55943845,   807.69167669])

In [74]:
data_test = pd.read_csv("test_new1.csv")
data_test = data_test.sample(n=3000)
data_test.head()

Store     Date  Dept  Temperature  Fuel_Price  CPI  Unemployment  \
11597      4  2012831    71           76           3  130             4   
2538       1  2012525    32           77           3  221             7   
7614       3  2011916    28           83           3  219             7   
6162       3   201035     7           53           2  214             7   
522        1  2010723    25           83           2  211             7   

       IsHoliday  Weekly_Sales  
11597          0          8235  
2538           0          8602  
7614           0            82  
6162           0          7229  
522            0          8238

In [75]:
#x1_test = data_test["Store"]
#x1_test = data_test["Date"]
#x1_test = data_test["Dept"]
x1_test = data_test["Temperature"]
x2_test = data_test["Fuel_Price"]
x3_test = data_test["CPI"]
x4_test = data_test["Unemployment"]
x5_test = data_test["IsHoliday"]
y_test = data_test["Weekly_Sales"]
m_test = y_test.size
print(x1_test.shape)
print(x2_test.shape)
print(x3_test.shape)
print(x4_test.shape)
print(x5_test.shape)
#print(x6_test.shape)
#print(x7_test.shape)

print(m_test)

(3000,)
(3000,)
(3000,)
(3000,)
(3000,)
3000


In [76]:
# Convert our variables datatype from series to array :

x1_test = np.array(x1_test)
x2_test = np.array(x2_test)
x3_test = np.array(x3_test)
x4_test = np.array(x4_test)
x5_test = np.array(x5_test)
#x6_test = np.array(x6_test)
#x7_test = np.array(x7_test)
y_test = np.array(y_test)

# number of our dataset

n_test = len(x1_test)
n_test

3000

In [77]:
# Create a “ones” matrix :

x_bias_test = np.ones((n_test,1))

# Reshape our data so that we can perform operations like addition and multiplication with x_bias

x1_new_test = np.reshape(x1_test,(n_test,1))
x2_new_test = np.reshape(x2_test,(n_test,1))
x3_new_test = np.reshape(x3_test,(n_test,1))
x4_new_test = np.reshape(x4_test,(n_test,1))
x5_new_test = np.reshape(x5_test,(n_test,1))
#x6_new_test = np.reshape(x6_test,(n_test,1))
#x7_new_test = np.reshape(x7_test,(n_test,1))

#Create a major matrix with all the columns:

x_new_test = np.append(x_bias_test,x1_new_test,axis=1)
x_new_test = np.append(x_new_test,x2_new_test,axis=1)
x_new_test = np.append(x_new_test,x3_new_test,axis=1)
x_new_test = np.append(x_new_test,x4_new_test,axis=1)
x_new_test = np.append(x_new_test,x5_new_test,axis=1)
#x_new_test = np.append(x_new_test,x6_new_test,axis=1)
#x_new_test = np.append(x_new_test,x7_new_test,axis=1)

print(x_new_test[4,5])



0.0


In [78]:
y_predict = np.zeros(m_test)
for i in range(m_test):
    sum = 0
    for n in range(6):
        sum += theta[n] * x_new_test[i][n]
    y_predict[i] = sum
print(y_predict)

print(x_new_test)
print(y_test)

[27785.96079545 16426.47670855 17248.51994343 ... 17304.25133394
 15638.22718015 13656.88069052]
[[  1.  76.   3. 130.   4.   0.]
 [  1.  77.   3. 221.   7.   0.]
 [  1.  83.   3. 219.   7.   0.]
 ...
 [  1.  40.   3. 194.   8.   0.]
 [  1.  81.   3. 223.   5.   0.]
 [  1.  48.   2. 211.   7.   0.]]
[8235 8602   82 ... 7960 4800 2029]


In [79]:
#evaluation
def WMAE(X_test, y_predict, y_test):
    sum = 0
    W = 0
    for i in range(m_test):
        if X_test[i][5] == 0:
            sum += abs(y_predict[i]-y_test[i])
            W += 1
        else:
            sum += 5 * abs(y_predict[i]-y_test[i])
            W += 5
    return sum / W

print(WMAE(x_new_test,y_predict,y_test))

17366.592315177837
